
package bank;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Aistė Mackevičiūtė
 */
public class GUIinestiPaimti extends javax.swing.JFrame {

    
     private final ZmogusKlientas klientas;
    private final Bankas bank;
    /**
     * Creates new form GUIinestiPaimti
     */
    public GUIinestiPaimti(Bankas bank, ZmogusKlientas klientas) {
        initComponents();
        this.klientas = klientas;
        this.bank = bank;
        jComboBoxSas.setModel(new DefaultComboBoxModel());
        List<Saskaita> saskaitos = klientas.getSaskaitos();
        for(Saskaita itm : saskaitos){
            jComboBoxSas.addItem(itm.toStringNr());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxSas = new javax.swing.JComboBox<>();
        jTextSuma = new javax.swing.JTextField();
        jLabelSas = new javax.swing.JLabel();
        jLabelLikutis = new javax.swing.JLabel();
        jLabelSuma = new javax.swing.JLabel();
        jButtonNuimti = new javax.swing.JButton();
        jButtonInesti = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBoxSas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxSas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSasActionPerformed(evt);
            }
        });

        jTextSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSumaActionPerformed(evt);
            }
        });

        jLabelSas.setText("Sąskaitos");

        jLabelLikutis.setText("Likutis");

        jLabelSuma.setText("Suma");

        jButtonNuimti.setText("Nuimti pinigus");
        jButtonNuimti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuimtiActionPerformed(evt);
            }
        });

        jButtonInesti.setText("Inesti pinigus");
        jButtonInesti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInestiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelLikutis)
                    .addComponent(jLabelSas)
                    .addComponent(jLabelSuma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxSas, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonInesti)
                .addGap(18, 18, 18)
                .addComponent(jButtonNuimti)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSas)
                    .addComponent(jComboBoxSas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelLikutis)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSuma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSuma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuimti)
                    .addComponent(jButtonInesti))
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSumaActionPerformed

    private void jButtonInestiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInestiActionPerformed
        String saskaita = jComboBoxSas.getSelectedItem().toString();
        String sumaString = jTextSuma.getText();
        
        double suma;
        try{
            
            suma = Double.parseDouble(sumaString);
            if(suma > 0 ){
                bank.pavedimasSQL(saskaita, null, suma);
            }
        
        }catch(NumberFormatException e){
          JOptionPane.showMessageDialog(null, "Sumą turi sudaryti tik skaičiai", "Info", JOptionPane.INFORMATION_MESSAGE);
        } catch (SaskaitaException ex) {
             Logger.getLogger(GUIinestiPaimti.class.getName()).log(Level.SEVERE, null, ex);
         } catch (SQLException ex) {
             Logger.getLogger(GUIinestiPaimti.class.getName()).log(Level.SEVERE, null, ex);
         }    }//GEN-LAST:event_jButtonInestiActionPerformed

    private void jComboBoxSasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSasActionPerformed
        String saskaita = jComboBoxSas.getSelectedItem().toString();
        Saskaita sas = klientas.getSaskaita(saskaita);
        jLabelLikutis.setText("Sąskaitos likutis:   " + sas.toStringLikutis() + " eur.");        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSasActionPerformed

    private void jButtonNuimtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuimtiActionPerformed
        
        String saskaita = jComboBoxSas.getSelectedItem().toString();
        String sumaString = jTextSuma.getText();
        
        double suma;
        try{
            
            suma = Double.parseDouble(sumaString);
            if(suma > 0 ){
                bank.pavedimasSQL(null, saskaita, suma);
            }
        
        }catch(NumberFormatException e){
          JOptionPane.showMessageDialog(null, "Sumą turi sudaryti tik skaičiai", "Info", JOptionPane.INFORMATION_MESSAGE);
        } catch (SaskaitaException ex) {
             Logger.getLogger(GUIinestiPaimti.class.getName()).log(Level.SEVERE, null, ex);
         } catch (SQLException ex) {
             Logger.getLogger(GUIinestiPaimti.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButtonNuimtiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIinestiPaimti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIinestiPaimti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIinestiPaimti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIinestiPaimti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             //   new GUIinestiPaimti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInesti;
    private javax.swing.JButton jButtonNuimti;
    private javax.swing.JComboBox<String> jComboBoxSas;
    private javax.swing.JLabel jLabelLikutis;
    private javax.swing.JLabel jLabelSas;
    private javax.swing.JLabel jLabelSuma;
    private javax.swing.JTextField jTextSuma;
    // End of variables declaration//GEN-END:variables
}
