
package bank;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Aistė Mackevičiūtė
 */
public class GUIklientas extends javax.swing.JFrame {

    /**
     * Creates new form Client
     */
    private Bankas bankas;
    public GUIklientas(Bankas bankas) {
        this.bankas = bankas;
        jLabelInfo.setVisible(false);
        initComponents();
        this.setLabels();
        
    }

    private void setLabels(){
        ZmogusKlientas zmogus = bankas.getVartotojas();
        this.jLabelVardas.setText("Vardas:  " + zmogus.getVardas());
        this.jLabelPavarde.setText("Pavardė:  " + zmogus.getPavarde());
        this.jLabelTelNr.setText("Tel. numeris:  " + zmogus.getTelNumeris());
        this.jLabelElPastas.setText("El. paštas:  " + zmogus.getElPastas());
        this.jLabel6.setText("Asmens kodas:  " + zmogus.getAsmensKodas());
        
    }
    private void setRedaguotiTrueTxt(){
        this.jTextElPastas.setVisible(true);
        this.jTextNaujasSlapt.setVisible(true);
        this.jTextPavarde.setVisible(true);
        this.jTextSenasSlapt.setVisible(true);
        this.jTextTelNr.setVisible(true);
        this.jTextVardas.setVisible(true);
        this.jButtonIsaugoti.setVisible(true);
        this.jLabelNaujasSlap.setVisible(true);
        this.jLabelSenasSlap.setVisible(true);
    }
    private void setRedaguotiFalseTxt(){
        this.jTextElPastas.setVisible(false);
        this.jTextNaujasSlapt.setVisible(false);
        this.jTextPavarde.setVisible(false);
        this.jTextSenasSlapt.setVisible(false);
        this.jTextTelNr.setVisible(false);
        this.jTextVardas.setVisible(false);
        this.jButtonIsaugoti.setVisible(false);
        this.jLabelNaujasSlap.setVisible(false);
        this.jLabelSenasSlap.setVisible(false);
        this.jTextElPastas.setText("");
        this.jTextNaujasSlapt.setText("");
        this.jTextPavarde.setText("");
        this.jTextSenasSlapt.setText("");
        this.jTextTelNr.setText("");
        this.jTextVardas.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabelPavarde = new javax.swing.JLabel();
        jLabelTelNr = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelElPastas = new javax.swing.JLabel();
        jButtonRedaguotiInfo = new javax.swing.JButton();
        jTextVardas = new javax.swing.JTextField();
        jTextPavarde = new javax.swing.JTextField();
        jTextTelNr = new javax.swing.JTextField();
        jTextElPastas = new javax.swing.JTextField();
        jLabelSenasSlap = new javax.swing.JLabel();
        jLabelNaujasSlap = new javax.swing.JLabel();
        jButtonIsaugoti = new javax.swing.JButton();
        jLabelError = new javax.swing.JLabel();
        jTextNaujasSlapt = new javax.swing.JTextField();
        jTextSenasSlapt = new javax.swing.JTextField();
        jLabelVardas = new javax.swing.JLabel();
        jLabelInfo = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        setResizable(false);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabelPavarde.setText("Pavardė:");

        jLabelTelNr.setText("Telefono numeris:");

        jLabel6.setText("Asmens kodas:");

        jLabelElPastas.setText("El. paštas:");

        jButtonRedaguotiInfo.setText("Redaguoti informaciją");
        jButtonRedaguotiInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRedaguotiInfoActionPerformed(evt);
            }
        });

        jTextVardas.setVisible(false);

        jTextPavarde.setVisible(false);

        jTextTelNr.setVisible(false);
        jTextTelNr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelNrActionPerformed(evt);
            }
        });

        jTextElPastas.setVisible(false);

        jLabelSenasSlap.setText("Senas slaptažodis:");
        jLabelSenasSlap.setVisible(false);

        jLabelNaujasSlap.setText("Naujas slaptažodis: ");
        jLabelNaujasSlap.setVisible(false);

        jButtonIsaugoti.setText("Išsaugoti pakeitimus");
        jButtonIsaugoti.setVisible(false);
        jButtonIsaugoti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIsaugotiActionPerformed(evt);
            }
        });

        jLabelError.setText("Error:");
        jLabelError.setText("");

        jTextNaujasSlapt.setVisible(false);
        jTextNaujasSlapt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNaujasSlaptActionPerformed(evt);
            }
        });

        jTextSenasSlapt.setVisible(false);
        jTextSenasSlapt.setMinimumSize(new java.awt.Dimension(6, 23));
        jTextSenasSlapt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSenasSlaptActionPerformed(evt);
            }
        });

        jLabelVardas.setText("Vardas:");

        jLabelInfo.setText("Atnaujinta sekmingai");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabelTelNr, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextTelNr, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelSenasSlap, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelElPastas, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelNaujasSlap, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(4, 4, 4))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonRedaguotiInfo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonIsaugoti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextSenasSlapt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextElPastas, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextNaujasSlapt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVardas, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPavarde, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextVardas, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPavarde, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVardas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextVardas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPavarde, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPavarde, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelNr, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextTelNr, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelElPastas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextElPastas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSenasSlap, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextSenasSlapt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNaujasSlap, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNaujasSlapt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRedaguotiInfo)
                    .addComponent(jButtonIsaugoti))
                .addGap(11, 11, 11)
                .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRedaguotiInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRedaguotiInfoActionPerformed
        this.setRedaguotiTrueTxt();
    }//GEN-LAST:event_jButtonRedaguotiInfoActionPerformed

    private void jTextSenasSlaptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSenasSlaptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSenasSlaptActionPerformed

    private void jTextNaujasSlaptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNaujasSlaptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNaujasSlaptActionPerformed

    private void jButtonIsaugotiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIsaugotiActionPerformed
        jLabelError.setText("");
        jLabelInfo.setVisible(false);
        jLabelInfo.setText("");
        String newVardas = jTextVardas.getText();
        String newPavarde = jTextPavarde.getText();
        String newElPastas = jTextElPastas.getText();
        String newTelNr = jTextTelNr.getText();
        String newSenasSlap = jTextSenasSlapt.getText();
        String newSlap = jTextNaujasSlapt.getText();
       try { 
           boolean atnaujinta = false;
            if(newVardas.length() > 0){
                System.out.println("Naujinu varda");
                this.bankas.atnaujintiKlientoInfoSQL("vardas", newVardas);
                this.bankas.getVartotojas().setVardas(newVardas);
                atnaujinta = true;
            }
            if(newPavarde.length() > 0){
                System.out.println("Naujinu pavarde");
                this.bankas.atnaujintiKlientoInfoSQL("pavarde", newPavarde);
                this.bankas.getVartotojas().setPavarde(newPavarde);
                atnaujinta = true;
            }
            if(newElPastas.length() > 0){
                System.out.println("Naujinu pasta");
                this.bankas.atnaujintiKlientoInfoSQL("elpastas", newElPastas);
                this.bankas.getVartotojas().setElPastas(newElPastas);
                atnaujinta = true;
            }
            if(newTelNr.length() > 0){
                if(newTelNr.matches("[0-9]+")){
                System.out.println("Naujinu telnr");
                this.bankas.atnaujintiKlientoInfoSQL("telnumeris", newTelNr);
                this.bankas.getVartotojas().setTelNumeris(newTelNr);
                atnaujinta = true;
                }else{
                   jLabelError.setText("Tel. numerį turi sudaryti tik skaičiai.");
                }
                
            }
            if(newSenasSlap.length() > 0 && newSlap.length() > 0){
                System.out.println("Naujinu slap");
                this.bankas.atnaujintiKlientoSlapSQL(newSenasSlap, newSlap);
                atnaujinta = true;
            }
            if(atnaujinta){
                jLabelInfo.setVisible(true);
                jLabelInfo.setText("Atnaujinta sekmingai");
            }else{
                jLabelInfo.setVisible(true);
                jLabelInfo.setText("Atnaujinimai neivyko");
            }
            this.setRedaguotiFalseTxt();
        } catch (SQLException ex) {
            jLabelInfo.setVisible(true);
            jLabelInfo.setText("Atnaujinimai neivyko");
            if(ex.getMessage().contains("new row for relation \"zmogus\" violates check constraint \"checkmail\"")){
                jLabelError.setText("Kladingas el. paštas.");
                
            }else if(ex.getMessage().contains("duplicate key value violates unique constraint \"unikaluspastas\"")){
                jLabelError.setText("Šis paštas jau naudojamas.");
        }else{
            Logger.getLogger(GUIklientas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }       
       this.setLabels();
    }//GEN-LAST:event_jButtonIsaugotiActionPerformed

    private void jTextTelNrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelNrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelNrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIklientas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIklientas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIklientas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIklientas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             //   new GUIklientas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIsaugoti;
    private javax.swing.JButton jButtonRedaguotiInfo;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelElPastas;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelNaujasSlap;
    private javax.swing.JLabel jLabelPavarde;
    private javax.swing.JLabel jLabelSenasSlap;
    private javax.swing.JLabel jLabelTelNr;
    private javax.swing.JLabel jLabelVardas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextElPastas;
    private javax.swing.JTextField jTextNaujasSlapt;
    private javax.swing.JTextField jTextPavarde;
    private javax.swing.JTextField jTextSenasSlapt;
    private javax.swing.JTextField jTextTelNr;
    private javax.swing.JTextField jTextVardas;
    // End of variables declaration//GEN-END:variables
}
