
package bank;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JLabel;

/**
 *
 * @author Aistė Mackevičiūtė
 */
public class GUInaujaSaskaita extends javax.swing.JFrame {

    private Bankas bankas;
    /**
     * Creates new form GUInaujaSaskaita
     */
    public GUInaujaSaskaita(Bankas bankas) {
        initComponents();
        this.bankas = bankas;
        jLabel1.setText("BANKAS " + this.bankas.getPavadinimas());
        jLabelError.setVisible(false);
        jLabelKreditas.setVisible(false);
        jTextKreditas.setVisible(false);
     //   this.jScrollPane1.setLayout(new ScrollPaneLayout);
        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
        //this.jScrollPane1.add(jPanel1);
        try{
            List <String> sa = bankas.getVisasSaskaitas();
            for(int i = 0; i < sa.size(); i++){
                JLabel jl = new JLabel(i +". " + sa.get(i) + "\n");
                jPanel1.add(jl);
                jScrollPane3.setViewportView(jPanel1);
              //  jTextArea1.setText(i +" " + sa.get(i) + "\n");
            }
            //jListSas = new JList(sa.toArray());
        } catch (SQLException ex) {
            Logger.getLogger(GUInaujaSaskaita.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        try {
            List <String> sar = bankas.getVisasSaskaitas();
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(GUInaujaSaskaita.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabelSasNr = new javax.swing.JLabel();
        jTextSasNr = new javax.swing.JTextField();
        jBoxTipai = new javax.swing.JComboBox<>();
        jLabelTipas = new javax.swing.JLabel();
        jLabelKreditas = new javax.swing.JLabel();
        jLabelLikutis = new javax.swing.JLabel();
        jTextLikutis = new javax.swing.JTextField();
        jTextKreditas = new javax.swing.JTextField();
        jLabelSas = new javax.swing.JLabel();
        jButtonSukurti = new javax.swing.JButton();
        jLabelError = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        jScrollPane2.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabelSasNr.setText("Sąskaitos numeris:");

        jBoxTipai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Debetine", "Kreditine", "Taupomoji" }));
        jBoxTipai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoxTipaiActionPerformed(evt);
            }
        });

        jLabelTipas.setText("Sąskaitos tipas:");

        jLabelKreditas.setText("Sąskaitos kereditas:");

        jLabelLikutis.setText("Saskaitos likutis:");

        jLabelSas.setText("Esami sąskaitos numeriai:");

        jButtonSukurti.setText("Sukurti");
        jButtonSukurti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSukurtiActionPerformed(evt);
            }
        });

        jLabelError.setText("Error:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setLabelFor(this);
        jLabel1.setText("BANKAS");

        jScrollPane3.setToolTipText("");
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelKreditas)
                            .addComponent(jLabelSasNr)
                            .addComponent(jLabelSas)
                            .addComponent(jLabelLikutis)
                            .addComponent(jLabelTipas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextSasNr)
                            .addComponent(jTextKreditas)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBoxTipai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextLikutis))))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSukurti)
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSasNr, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextSasNr, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBoxTipai, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextLikutis, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLikutis, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelKreditas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextKreditas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSukurti, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBoxTipaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoxTipaiActionPerformed
        if("Kreditine".equals(jBoxTipai.getSelectedItem().toString())){
            jLabelKreditas.setVisible(true);
            jTextKreditas.setVisible(true);
        }else{
            jLabelKreditas.setVisible(false);
            jTextKreditas.setVisible(false);
        }
    }//GEN-LAST:event_jBoxTipaiActionPerformed

    private void jButtonSukurtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSukurtiActionPerformed
        String sasNr = jTextSasNr.getText();
        String kreditas = jTextKreditas.getText();
        String likutis = jTextLikutis.getText();
        String tipas = jBoxTipai.getSelectedItem().toString();
        double kreditasInt = 0.0;
        if("Kreditine".equals(tipas)){
            jLabelKreditas.setVisible(true);
            jTextKreditas.setVisible(true);
        }else{
            jLabelKreditas.setVisible(false);
            jTextKreditas.setVisible(false);
            jTextKreditas.setText("0");
        }
        try{
            if(kreditas.length() > 0){
                kreditasInt = Double.parseDouble(kreditas);
                if(kreditasInt < 0){
                    jLabelError.setText("Kreditą turi būti teigiamas skaičius");
                }
            }
        }catch(NumberFormatException e){
            jLabelError.setVisible(true);
            jLabelError.setText("Kreditą turi sudaryti skaičiai");
        }
        double likutisDouble;
        try{ 
            if(likutis.length() > 0){
                likutisDouble = Double.parseDouble(likutis);
                if(likutisDouble >= 0){
                    if(kreditasInt >= 0){
                        System.out.println("Kuriu saskaita");
                       bankas.sukurtiSaskaitaSQL(sasNr, tipas, likutisDouble, kreditasInt);
                       jLabelError.setVisible(true);
                       jLabelError.setText("Sąskaita sekmingai sukurta");
                       
                    }
                }else{
                    jLabelError.setVisible(true);
                    jLabelError.setText("Likutį turi būti teigimas skaičius");
                }
            }
        }catch(NumberFormatException e){
            jLabelError.setVisible(true);
            jLabelError.setText("Likutį turi sudaryti skaičiai");
        } catch (SQLException ex) {
            if(ex.getMessage().contains("duplicate key value violates unique constraint \"saskaita_pkey\"")){
                jLabelError.setVisible(true);
               jLabelError.setText("Tokia sąskaita jau egzistuoja"); 
            }else{
                Logger.getLogger(GUInaujaSaskaita.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       
        
        
    }//GEN-LAST:event_jButtonSukurtiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUInaujaSaskaita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUInaujaSaskaita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUInaujaSaskaita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUInaujaSaskaita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new GUInaujaSaskaita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jBoxTipai;
    private javax.swing.JButton jButtonSukurti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelKreditas;
    private javax.swing.JLabel jLabelLikutis;
    private javax.swing.JLabel jLabelSas;
    private javax.swing.JLabel jLabelSasNr;
    private javax.swing.JLabel jLabelTipas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextKreditas;
    private javax.swing.JTextField jTextLikutis;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField jTextSasNr;
    // End of variables declaration//GEN-END:variables
}
