
package bank;


import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Aistė Mackevičiūtė
 */
public class GUIregForma extends javax.swing.JFrame {

    /**
     * Creates new form GuiRegForma
     */
    public GUIregForma(Bankas bank) {
        initComponents();
        this.bank = bank;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtVardas = new javax.swing.JTextField();
        TxtPavarde = new javax.swing.JTextField();
        TxtAK = new javax.swing.JTextField();
        jLabelVardas = new javax.swing.JLabel();
        jLabelPavarde = new javax.swing.JLabel();
        jLabelAk = new javax.swing.JLabel();
        txtNumeris = new javax.swing.JTextField();
        jLabelTelNr = new javax.swing.JLabel();
        txtPastas = new javax.swing.JTextField();
        jLabelElPastas = new javax.swing.JLabel();
        jButtonOk = new javax.swing.JButton();
        jTxtPrisijungimoVardas = new javax.swing.JTextField();
        jTxtSlaptazodis = new javax.swing.JTextField();
        jLabelPriVardas = new javax.swing.JLabel();
        jLabelSlaptazodis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TxtPavarde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPavardeActionPerformed(evt);
            }
        });

        jLabelVardas.setText("Vardas");

        jLabelPavarde.setText("Pavarde");

        jLabelAk.setText("Asmens kodas");

        jLabelTelNr.setText("Tel. numeris");

        jLabelElPastas.setText("El. paštas");

        jButtonOk.setText("OK");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jTxtPrisijungimoVardas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPrisijungimoVardasActionPerformed(evt);
            }
        });

        jLabelPriVardas.setText("Prisijungimo Vardas");

        jLabelSlaptazodis.setText("Slaptažods");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonOk, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVardas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelTelNr, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAk, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelElPastas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPriVardas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelSlaptazodis, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPavarde, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtSlaptazodis)
                            .addComponent(jTxtPrisijungimoVardas)
                            .addComponent(txtPastas, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(txtNumeris)
                            .addComponent(TxtPavarde, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtAK, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtVardas, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVardas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVardas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPavarde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPavarde))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtAK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumeris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelNr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPastas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelElPastas))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtPrisijungimoVardas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPriVardas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtSlaptazodis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSlaptazodis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButtonOk)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtPavardeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPavardeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPavardeActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        try {
            String vardas = txtVardas.getText();
            String pavarde = TxtPavarde.getText();
            String asmkod = TxtAK.getText();
            String elPastas = txtPastas.getText();
            String numeris = txtNumeris.getText();
            String prisijungimas = jTxtPrisijungimoVardas.getText();
            String slapt = jTxtSlaptazodis.getText();
            
            bank.pridetiKlientaSQL(vardas, pavarde, asmkod, numeris, elPastas, prisijungimas, slapt);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(GUIregForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jTxtPrisijungimoVardasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPrisijungimoVardasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPrisijungimoVardasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIregForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIregForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIregForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIregForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new GuiRegForma().setVisible(true);
            }
        });
    }
    
    private Bankas bank;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtAK;
    private javax.swing.JTextField TxtPavarde;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabelAk;
    private javax.swing.JLabel jLabelElPastas;
    private javax.swing.JLabel jLabelPavarde;
    private javax.swing.JLabel jLabelPriVardas;
    private javax.swing.JLabel jLabelSlaptazodis;
    private javax.swing.JLabel jLabelTelNr;
    private javax.swing.JLabel jLabelVardas;
    private javax.swing.JTextField jTxtPrisijungimoVardas;
    private javax.swing.JTextField jTxtSlaptazodis;
    private javax.swing.JTextField txtNumeris;
    private javax.swing.JTextField txtPastas;
    private javax.swing.JTextField txtVardas;
    // End of variables declaration//GEN-END:variables
}
