
package bank;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JLabel;

/**
 *
 * @author Aistė Mackevičiūtė
 */
public class GUIregistracija extends javax.swing.JFrame {

    /**
     * Creates new form account
     */
    public GUIregistracija(Bankas bankas, int nr) {
        initComponents();
        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
        try{
            JLabel jl;
            List <String> sa;
            switch(nr) {
                case(1):
                    jl = new JLabel("Saskaitos numeris | Likutis | Kreditas | Bankas \n");
                    jPanel1.add(jl);
                    jScrollPane2.setViewportView(jPanel1);
                    sa = bankas.getVisasSaskaitasSuLikuciais();
                    for(int i = 0; i < sa.size(); i++){
                        jl = new JLabel(sa.get(i) + "\n");
                        jPanel1.add(jl);
                        jScrollPane2.setViewportView(jPanel1);
                    }
                    break;
                case(2) :
                    jl = new JLabel("Saskaitos numeris | Likutis | Kreditas | Bankas \n");
                    jPanel1.add(jl);
                    jScrollPane2.setViewportView(jPanel1);
                    sa = bankas.getVisasSaskaitasVartotojoSuLikuciais();
                    for(int i = 0; i < sa.size(); i++){
                        jl = new JLabel(sa.get(i) + "\n");
                        jPanel1.add(jl);
                        jScrollPane2.setViewportView(jPanel1);
                    }
                    break;
                case(3):
                    jl = new JLabel("Jūs atlikote šias transakcijas \n");
                    jPanel1.add(jl);
                    jl = new JLabel("Aliko transakciją | Gavo transakciją | Transakcijos suma \n");
                    jPanel1.add(jl);
                    jScrollPane2.setViewportView(jPanel1);
                    sa = bankas.getTransakcijuSarasasIssiustu();
                    for(int i = 0; i < sa.size(); i++){
                        jl = new JLabel(sa.get(i) + "\n");
                        jPanel1.add(jl);
                        jScrollPane2.setViewportView(jPanel1);
                    }
                    jl = new JLabel("Jūs gavote šias transakcijas \n");
                    jPanel1.add(jl);
                    jl = new JLabel("Aliko transakciją | Gavo transakciją | Transakcijos suma \n");
                    jPanel1.add(jl);
                    jScrollPane2.setViewportView(jPanel1);
                    sa.clear();
                    sa = bankas.getTransakcijuSarasasGautu();
                    for(int i = 0; i < sa.size(); i++){
                        jl = new JLabel(sa.get(i) + "\n");
                        jPanel1.add(jl);
                        jScrollPane2.setViewportView(jPanel1);
                    }
                    break;
                
                    
            }
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(GUInaujaSaskaita.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIregistracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIregistracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIregistracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIregistracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new GUIregistracija().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
